"""initial schema

Revision ID: f0f92986b448
Revises: 
Create Date: 2026-05-29 08:47:47.143326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'f0f92986b448'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # The vector type used by chunk_embeddings requires the pgvector extension.
    # This is a no-op on databases that already have it (and on SQLite the
    # statement is skipped because the dialect has no such extension).
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('course_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=False),
    sa.Column('course_title', sa.String(length=200), nullable=False),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('credit', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('course_id')
    )
    op.create_index(op.f('ix_courses_course_code'), 'courses', ['course_code'], unique=True)
    op.create_table('learning_weeks',
    sa.Column('week_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('directory_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('week_id')
    )
    op.create_index(op.f('ix_learning_weeks_week_number'), 'learning_weeks', ['week_number'], unique=True)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('learning_resources',
    sa.Column('resource_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('week_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['week_id'], ['learning_weeks.week_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index('idx_learning_resource_week_order', 'learning_resources', ['week_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_learning_resources_title'), 'learning_resources', ['title'], unique=False)
    op.create_table('search_logs',
    sa.Column('log_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('search_type', sa.String(length=20), nullable=True),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index('idx_search_logs_user_date', 'search_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_search_logs_created_at'), 'search_logs', ['created_at'], unique=False)
    op.create_table('topics',
    sa.Column('topic_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id')
    )
    op.create_index(op.f('ix_topics_topic_name'), 'topics', ['topic_name'], unique=False)
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('course_code', sa.String(length=20), nullable=True),
    sa.Column('topic_name', sa.String(length=100), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('exam_type', sa.String(length=50), nullable=True),
    sa.Column('difficulty', sa.String(length=20), nullable=True),
    sa.Column('marks', sa.Integer(), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('answer_reference', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index('idx_questions_course_topic', 'questions', ['course_id', 'topic_id'], unique=False)
    op.create_index('idx_questions_year_difficulty', 'questions', ['year', 'difficulty'], unique=False)
    op.create_index(op.f('ix_questions_difficulty'), 'questions', ['difficulty'], unique=False)
    op.create_index(op.f('ix_questions_year'), 'questions', ['year'], unique=False)
    op.create_table('resources',
    sa.Column('resource_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=200), nullable=True),
    sa.Column('year_published', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.course_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.topic_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_index(op.f('ix_resources_title'), 'resources', ['title'], unique=False)
    op.create_table('resource_chunks',
    sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.resource_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('idx_chunk_resource_index', 'resource_chunks', ['resource_id', 'chunk_index'], unique=False)
    op.create_table('chunk_embeddings',
    sa.Column('embedding_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_id', sa.Integer(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['resource_chunks.chunk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('embedding_id'),
    sa.UniqueConstraint('chunk_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chunk_embeddings')
    op.drop_index('idx_chunk_resource_index', table_name='resource_chunks')
    op.drop_table('resource_chunks')
    op.drop_index(op.f('ix_resources_title'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_questions_year'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty'), table_name='questions')
    op.drop_index('idx_questions_year_difficulty', table_name='questions')
    op.drop_index('idx_questions_course_topic', table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_topics_topic_name'), table_name='topics')
    op.drop_table('topics')
    op.drop_index(op.f('ix_search_logs_created_at'), table_name='search_logs')
    op.drop_index('idx_search_logs_user_date', table_name='search_logs')
    op.drop_table('search_logs')
    op.drop_index(op.f('ix_learning_resources_title'), table_name='learning_resources')
    op.drop_index('idx_learning_resource_week_order', table_name='learning_resources')
    op.drop_table('learning_resources')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_learning_weeks_week_number'), table_name='learning_weeks')
    op.drop_table('learning_weeks')
    op.drop_index(op.f('ix_courses_course_code'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
